#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');

const softwareDir = path.resolve(__dirname, '..');
globalThis.AltiviewVfrData = { points: [] };
const source = require(path.join(softwareDir, 'aero_data.js'));

const frenchAirportPrefix = /^(LF|FR|TF|SO|FM|NT|NW)/;
const inBox = (p, south, west, north, east) =>
    Number.isFinite(p.lat) && Number.isFinite(p.lng) &&
    p.lat >= south && p.lat <= north && p.lng >= west && p.lng <= east;
const inFrenchCoverage = p =>
    inBox(p, 41, -6, 52, 10) ||
    inBox(p, 14, -63, 18.5, -60) ||
    inBox(p, 2, -55, 6, -51) ||
    inBox(p, -23, 42, -10, 57) ||
    inBox(p, -28, -155, 0, -130) ||
    inBox(p, -24, 160, -18, 168);

const data = {
    airports: source.AIRPORTS.filter(a => frenchAirportPrefix.test(a.icao || '') || inFrenchCoverage(a)),
    airspaces: source.AIRSPACES.filter(a => a.country === 'FR'),
    fis: source.FIS_SIV_AREAS.filter(a => a.country === 'FR'),
    navaids: source.NAVAIDS.filter(inFrenchCoverage)
};

const runtime = `/** Generated by tools/build_fr_aero_data.cjs from aero_data.js. */
(function(root,factory){const data=factory();if(typeof module==='object'&&module.exports)module.exports=data;root.AeroData=data;})(typeof globalThis!=='undefined'?globalThis:this,function(){
const AIRPORTS=${JSON.stringify(data.airports)};
const AIRSPACES=${JSON.stringify(data.airspaces)};
const FIS_SIV_AREAS=${JSON.stringify(data.fis)};
const VFR_WAYPOINTS=(typeof globalThis!=='undefined'&&globalThis.AltiviewVfrData&&globalThis.AltiviewVfrData.points)||[];
const NAVAIDS=${JSON.stringify(data.navaids)};
function isPointInPolygon(point,vs){const x=point[0],y=point[1];let inside=false;for(let i=0,j=vs.length-1;i<vs.length;j=i++){const xi=vs[i][0],yi=vs[i][1],xj=vs[j][0],yj=vs[j][1];const hit=((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi)+xi);if(hit)inside=!inside;}return inside;}
function findAirspacesAt(lat,lng){return AIRSPACES.filter(sp=>{const b=sp.bbox;if(b&&(lat<b[0]||lng<b[1]||lat>b[2]||lng>b[3]))return false;return isPointInPolygon([lat,lng],sp.coordinates);});}
function filterAirspacesByAltitude(altFt){if(!altFt||altFt<=0)return AIRSPACES;return AIRSPACES.filter(sp=>altFt>=(sp.floorFt??0)&&altFt<=(sp.ceilingFt??99999));}
function searchAll(query){if(!query||typeof query!=='string')return[];const q=query.trim().toUpperCase();if(!q)return[];const out=[];
for(const a of AIRPORTS){const code=(a.icao||'').toUpperCase(),name=(a.name||'').toUpperCase(),city=(a.city||'').toUpperCase();let score=code===q?120:code.startsWith(q)?100:name.includes(q)?75:city.includes(q)?55:0;if(score)out.push({type:'airport',category:'Aérodrome',title:code+' — '+a.name,sub:(a.city||'')+' • '+a.alt+' ft',lat:a.lat,lng:a.lng,score,data:a});}
for(const sp of AIRSPACES){const name=(sp.name||'').toUpperCase();let score=name===q?100:name.startsWith(q)?80:name.includes(q)?65:0;if(score){const lat=sp.bbox?(sp.bbox[0]+sp.bbox[2])/2:sp.coordinates[0][0],lng=sp.bbox?(sp.bbox[1]+sp.bbox[3])/2:sp.coordinates[0][1];out.push({type:'airspace',category:sp.type,title:sp.name,sub:sp.type+' Class '+sp.class+' • '+sp.floor+' ➔ '+sp.ceiling,lat,lng,score,data:sp});}}
for(const wp of VFR_WAYPOINTS){const name=(wp.name||'').toUpperCase(),desc=(wp.desc||'').toUpperCase(),label=((wp.airport||'')+' '+(wp.code||'')).trim().toUpperCase();let score=label===q||name===q?110:label.startsWith(q)?95:name.includes(q)||label.includes(q)?75:desc.includes(q)?60:0;if(score)out.push({type:'vfr',category:'VFR · consulter la VAC',title:label,sub:wp.name+' · '+(wp.desc||'Repère publié SIA'),lat:wp.lat,lng:wp.lng,score,data:wp});}
for(const n of NAVAIDS){const ident=(n.ident||'').toUpperCase(),name=(n.name||'').toUpperCase();let score=ident===q?95:ident.startsWith(q)?80:name.includes(q)?55:0;if(score)out.push({type:'navaid',category:n.type,title:n.ident+' ('+n.name+')',sub:n.type+' • '+n.freq+' • Morse: '+n.morse,lat:n.lat,lng:n.lng,score,data:n});}
return out.sort((a,b)=>b.score-a.score).slice(0,15);}
return {AIRPORTS,AIRSPACES,FIS_SIV_AREAS,VFR_WAYPOINTS,NAVAIDS,isPointInPolygon,findAirspacesAt,filterAirspacesByAltitude,searchAll};
});
`;

const target = path.join(softwareDir, 'data', 'aero-fr.js');
fs.writeFileSync(target, runtime);
console.log(`Wrote ${path.relative(softwareDir, target)}: ${data.airports.length} airports, ${data.airspaces.length} airspaces, ${data.navaids.length} navaids.`);
